# Jaime Ariel Chitay
# 19002065

# Parte 1

In [10]:
def operacion_not(x1):
    parametros = [-1,1]
    return int(x1*parametros[0]* parametros[1]>0)
testx = 0
operacion_not(testx)

0

In [11]:
def  operacion_or(x1,x2):
  parametros = [1,1,0]

  return  int(x1*parametros[0]  + x2*parametros[1] + parametros[2] > 0)

testx1 = 1
testx2 = 1

operacion_or(testx1,testx2)

1

In [12]:
def  operacion_and(x1,x2):
  parametros = [1,1,-1]

  return  int(x1*parametros[0]  + x2*parametros[1] + parametros[2] > 0)

testx1 = 0
testx2 = 1

operacion_and(testx1,testx2)

0

In [13]:
def operacion_xor(x1,x2):
  temp1 = operacion_and(x1,x2)
  temp2 = operacion_or(x1,x2)

  nand_temp = operacion_not(temp1)

  temp_3 = operacion_and(nand_temp,temp2)

  return temp_3

testx1 = 1
testx2 = 1

operacion_xor(testx1,testx2)

0

# Parte 2

![network](network.png)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Activación Step
def heaviside(x):
    return (x >= 0).astype(np.float)

# Función de activación ReLU
def ReLU(x):
    return np.maximum(0., x)

# Activación sigmoide
def sigmoid(x):
    return 1/(1+np.exp(-x))

def ReLU_gradient(x):
    return (x > 0).astype(np.float)

def linearAct(x):
    return x

def addBias(x):
    return np.vstack((np.ones(x.shape[1]), x))

def removeBias(x):
    return x[1:, :].reshape(-1, x.shape[1])

In [3]:
sigmoid(np.array([-1, 0., 1., 2.]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

In [4]:
ReLU(np.array([-1, 0., 1., 2.]))

array([0., 0., 1., 2.])

In [5]:
ReLU_gradient(np.array([-1, 0., 1., 2.]))

array([0., 0., 1., 1.])

# Conjunto de datos de entrenamiento

La red neuronal debe aprender la función XOR, por lo tanto, utilizaremos dos entradas y sus respectivas salidas conocidas.

In [6]:
Xtrain = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
Xtrain

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [7]:
Ytrain = np.array([0., 1., 1., 0.]).reshape(-1, 1)
Ytrain

array([[0.],
       [1.],
       [1.],
       [0.]])

In [8]:
Xtrain.T, Ytrain.T

(array([[0., 0., 1., 1.],
        [0., 1., 0., 1.]]), array([[0., 1., 1., 0.]]))

# Matrices de pesos sinápticos
Definimos los pesos sinápticos iniciales de la red neuronal.

In [9]:
# Capa oculta 1
k1 = 3
Theta1 = np.random.normal(scale=0.1, size=(k1, 3))
Theta1

array([[-0.0679132 ,  0.02169539, -0.11752514],
       [-0.03905631, -0.04255749, -0.05379981],
       [-0.0378277 ,  0.13894588, -0.0998927 ]])

In [10]:
# Capa oculta 2
k2 = 2
Theta2 = np.random.normal(scale=0.1, size=(k2, k1+1))
Theta2

array([[ 0.02806555, -0.04070303,  0.0673602 ,  0.04768754],
       [-0.07951799, -0.06323192, -0.04291594, -0.07900084]])

In [11]:
# Capa de salida
Theta3 = np.random.normal(scale=0.1, size=(1, 3))
Theta3

array([[-0.16715231,  0.05902747,  0.26639478]])

# Forward propagation y cómputo de la salida

In [12]:
Xtrain.T, Xtrain.T.shape

(array([[0., 0., 1., 1.],
        [0., 1., 0., 1.]]), (2, 4))

In [13]:
def forwardProp(X, Theta1, Theta2, Theta3, retHidden=False):
    # Primera capa oculta
    z_2 = np.matmul(Theta1, addBias(X))
    a_2 = ReLU(z_2)
    # Segunda capa oculta
    z_3 = np.matmul(Theta2, addBias(a_2))
    a_3 = ReLU(z_3)
    # Capa de salida
    z_4 = np.matmul(Theta3, addBias(a_3))
    a_4 = linearAct(z_4)
    
    if retHidden:
        return a_3, a_4
    
    return a_4

In [14]:
forwardProp(Xtrain.T, Theta1, Theta2, Theta3)

array([[-0.10812484, -0.10812484, -0.10812484, -0.10812484]])

In [15]:
forwardProp(np.array([100., 50.]).reshape(-1, 1), Theta1, Theta2, Theta3)

array([[-0.10812484]])