# Maldición de dimensionalidad y polynomial features

## 19002065 Ariel Chitay

In [4]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
import pandas as pd

# 1 Variable

In [7]:
x = np.random.rand(5,1)
x=pd.DataFrame(x)
x

0
0  0.852698
1  0.359691
2  0.837309
3  0.862039
4  0.434221

In [8]:
poly = PolynomialFeatures(3)
poly.fit_transform(x)

array([[1.        , 0.8526979 , 0.7270937 , 0.61999127],
       [1.        , 0.35969064, 0.12937736, 0.04653582],
       [1.        , 0.83730853, 0.70108557, 0.58702493],
       [1.        , 0.86203925, 0.74311167, 0.64059143],
       [1.        , 0.43422062, 0.18854754, 0.08187123]])

# 2 Variables

In [9]:
x1 = np.random.rand(5,2)
pd.DataFrame(x1)

0         1
0  0.753876  0.496817
1  0.835113  0.919131
2  0.502708  0.760770
3  0.321346  0.425710
4  0.893715  0.964196

In [10]:
poly1 = PolynomialFeatures(3)
poly1.fit_transform(x1)

array([[1.        , 0.75387638, 0.49681708, 0.5683296 , 0.37453866,
        0.24682721, 0.42845026, 0.28235585, 0.18607721, 0.12262798],
       [1.        , 0.83511314, 0.91913106, 0.69741396, 0.76757843,
        0.84480191, 0.58241956, 0.64101483, 0.70550517, 0.77648367],
       [1.        , 0.5027077 , 0.76077022, 0.25271503, 0.38244505,
        0.57877133, 0.12704179, 0.19225807, 0.29095281, 0.44031199],
       [1.        , 0.32134564, 0.42571037, 0.10326302, 0.13680017,
        0.18122932, 0.03318312, 0.04396014, 0.05823725, 0.0771512 ],
       [1.        , 0.89371532, 0.9641956 , 0.79872706, 0.86171638,
        0.92967316, 0.71383461, 0.77012912, 0.83086314, 0.89638678]])

# 3 variables

In [11]:
x2 = np.random.rand(5,3)
pd.DataFrame(x2)

0         1         2
0  0.864082  0.191508  0.953396
1  0.846687  0.719857  0.189122
2  0.768482  0.942694  0.727194
3  0.929440  0.328042  0.532204
4  0.203560  0.731935  0.119339

In [12]:
poly2 = PolynomialFeatures(3)
poly2.fit_transform(x1)

array([[1.        , 0.75387638, 0.49681708, 0.5683296 , 0.37453866,
        0.24682721, 0.42845026, 0.28235585, 0.18607721, 0.12262798],
       [1.        , 0.83511314, 0.91913106, 0.69741396, 0.76757843,
        0.84480191, 0.58241956, 0.64101483, 0.70550517, 0.77648367],
       [1.        , 0.5027077 , 0.76077022, 0.25271503, 0.38244505,
        0.57877133, 0.12704179, 0.19225807, 0.29095281, 0.44031199],
       [1.        , 0.32134564, 0.42571037, 0.10326302, 0.13680017,
        0.18122932, 0.03318312, 0.04396014, 0.05823725, 0.0771512 ],
       [1.        , 0.89371532, 0.9641956 , 0.79872706, 0.86171638,
        0.92967316, 0.71383461, 0.77012912, 0.83086314, 0.89638678]])

## Conclusión
La maldición de la dimensión nos enseña que la variabilidad de las distancias entre nuestros datos disminuye exponencialmente con el número de dimensiones (features).

Esta maldición afecta a las técnicas que estén basadas en distancias tales como agrupamiento (clustering), los vecinos más cercanos (k-NN), algunas técnicas de detección de outliers, etc.

Para mitigar los efectos de esta «maldición» podemos utilizar técnicas de reducción de la dimensionalidad y / o aumentar (exponencialmente) la cantidad de datos.