# Jaime Ariel Chitay <br> 19002065 <br> Ciencia de datos en python

# Diferencias entre np.matrix y np.array
 

## np.array

Para hacer una numpy matriz, se debe usar una función llamada ` np.array()`. Todo lo que se necesita hacer es pasarle una lista y, opcionalmente, también puede especificar el tipo de datos de los datos.<br> 

Se debe recordar que para trabajar con la np.array(), debe asegurar de que la biblioteca numpy esté presente en su entorno. La biblioteca NumPy sigue una convención de importación: cuando importa esta biblioteca, debe asegurarse de que la importe como np.

In [27]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.zeros((2,2,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [15]:
np.random.random((3,3))

array([[0.24901742, 0.94568551, 0.25033387],
       [0.05394608, 0.35931764, 0.68817374],
       [0.01512626, 0.24199767, 0.54616308]])

In [16]:
np.empty((2,2))


array([[0.39654626, 0.65204941],
       [0.62361678, 0.22588782]])

In [12]:
np.full((2,2),7)


array([[7, 7],
       [7, 7]])

In [19]:
# Create an array of evenly-spaced values
np.arange(10,25,5)

array([10, 15, 20])

In [20]:
# Create an array of evenly-spaced values
np.linspace(0,2,9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

# np.matrix

Se le ingresa una lista o un texto y lo convierte a una matriz, esta función no es recomendable usarla debido a que 
,incluso para el álgebra lineal. En su lugar, utilice matrices regulares. La clase puede ser eliminada en el futuro.

In [24]:
print(np.matrix([[1, 2], [3, 4]]))
print(np.matrix('1 2; 3 4'))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [32]:
np.matrix('1, 2')

matrix([[1, 2]])

# Parámetros de un array

### numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)¶

# Parámetros de un matrix

### class numpy.matrix( data , dtype = None , copy = True ) 
